重开： `GBC 2022 Autumn` 规则书
RushFTK/osu-wiki pull request #7
Opened 2022-09-20 12:43 UTC by RushFTK

- refernce commit 77ca3428d2 / 6e3e6002d3

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2022-09-20 13:45 UTC, RushFTK reviewed
add missed modified

2022-09-20 13:45 UTC, RushFTK commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +4. Tournament staff members must not participate as players in the tournament.
```suggestion
4. [Tournament staff](https://osu.ppy.sh/wiki/en/Tournaments/Official_support#what-is-considered-staff) members must not participate as players in the tournament.
```

2022-09-20 14:25 UTC, yobrevelc requested changes
Manage of wiki

2022-09-20 14:25 UTC, yobrevelc commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +| Qualifier showcase | 2022-10-07 (20:00 UTC+8) |
change to 2022-10-08(20:00 UTC+8)

2022-09-20 14:25 UTC, yobrevelc commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +| Mappool selector | *TBA* |
[GB]yobrevelc,Hylotl,[GB]Luoxuan0327,[GB]Mafufu,[GB]Sanae,Yueast 2018

2022-09-20 14:25 UTC, yobrevelc commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +8. Referee **nolonger** have right to temporary modify rules on matches they responsible for.
delete

2022-09-20 14:25 UTC, yobrevelc commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +6. Host have rights to request VOD at any point.
delete

2022-09-20 14:25 UTC, yobrevelc commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +5. If no referee is available at match time, the match will be postponed.
delete

2022-09-20 14:25 UTC, yobrevelc commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +   - This rule is not to be abused. Referees may veto a rematch request if they find that this is the case.
```suggestion
   - This rule should not to be abused. Referees may veto a rematch request if they find that this is the case.
```

2022-09-20 14:25 UTC, yobrevelc commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +1. Qualifier stage added, for deteriment captain role, result will be used in Drafting phase.
```suggestion
1. Qualifier stage added, for determining captain role, result will be used in Drafting phase.
```

2022-09-20 14:25 UTC, yobrevelc commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +2. Player not being picked on Drafting phase will be eliminated.
```suggestion
2. There will be some players been eliminated in qualifier and drafing phase.
```

2022-09-20 14:25 UTC, yobrevelc commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +3. Player can't be banned if he never played a game in a match.
```suggestion
3. Player can't be banned in a match until he has finished a game in this match.
```

2022-09-20 14:25 UTC, yobrevelc commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +1. In the Qualifier stage, all players will play a specific pool designed by the mappool selectors.
```suggestion
1. In the Qualifier stage, all players will play a specific mappool designed by the mappool selectors and mappool helpers.
```

2022-09-20 14:25 UTC, yobrevelc commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +   - Higher score will have higher chance to be picked on Drafting phase. player will be eliminated if not being picked on Drafting phase.
```suggestion
   - Higher score will have higher chance to be picked on Drafting phase. player will be eliminated if he got too low in qualifier and not being picked on Drafting phase.
```

2022-09-20 14:25 UTC, yobrevelc commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +16队 -> 三轮瑞士轮 + 附加轮（2-1 vs 1-2） -> 8队DE，3+1+4=8周
```suggestion
16队 -> 三轮瑞士轮 + 附加轮（只保留2-1和1-2的队伍） -> 8队DE，3+1+4=8周
```

2022-09-20 14:25 UTC, yobrevelc commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +1. Following the Qualifier stage, all player should pricipate a phase to formed teams , called `Drafting phase`, unpicked player will be eliminated from the tournament.
```suggestion
1. Following the Qualifier stage, all player should participate a phase to formed teams , called `Drafting phase`, unpicked player will be eliminated from the tournament.
```

2022-09-20 14:25 UTC, yobrevelc commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +| Qualifier stage | 2022-10-15/2022-10-16 |
```suggestion
| Qualifier stage | 2022-10-15/2022-10-16 |
| Qualifier result showcase | 2022-10-21 |
```

2022-09-20 14:25 UTC, yobrevelc commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +| Drafting phase | 2022-10-22 (20:00 UTC+8) |
```suggestion
| Drafting phase & Regular stage showcase| 2022-10-23 (20:00 UTC+8) |
```

2022-09-20 14:25 UTC, yobrevelc commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +   - Fewest beatmaps lost
```suggestion
   - Fewest beatmaps lost
   - Highest total matches score difference(in the whole regular stage)
```

2022-09-20 14:25 UTC, yobrevelc commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +   - The winner of the `!roll` starts picking the first beatmap of the match.
```suggestion
   - The winner of the `!roll` could choose to pick first or ban first of the match. The other choose will be used by loser team.
```

2022-09-20 14:25 UTC, yobrevelc commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +   - If player never played on this match, he **can't** be banned.
```suggestion
   - A player **can't** be banned until he finished playing a game on this match.
```

2022-09-20 14:25 UTC, yobrevelc commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +6. Teams will have 2 minutes to pick or ban a beatmap, 1 minute to ban an opposing player, and 2 minutes to get ready. If a team takes more time than allotted, the procedures adopted will be as follo
```suggestion
6. Teams will have 2 minutes to pick a beatmap and ban an opposing player , and 2 minutes to get ready. If a team takes more time than allowed, the procedures adopted will be as follows:
 -  Pick beatmaps and ban players should be sent at a single message, if a team continue be slow at banning, referees have rights to ignore this ban.
```

2022-09-20 14:25 UTC, yobrevelc commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +   - Regular stage Round 3 and Quarterfinals use mappool #2.
```suggestion
   - Regular stage Round 3 and Round 4 use mappool #2.
```

2022-09-20 14:25 UTC, yobrevelc commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +1. There will be three separate mappools.
```suggestion
1. There will be five separate mappools.(视情况修改)
```

2022-09-20 14:25 UTC, yobrevelc commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +   - **Players that don't pick a time slot by Wednesday, 10 October 23:59 UTC+8 will be disqualified from the competition.**
```suggestion
   - **Players that don't pick a time slot by Wednesday, 11 October 23:59 UTC+8 will be disqualified from the competition.**
```

2022-09-20 14:25 UTC, yobrevelc commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +3. All matches will be held between Saturday 0:00 and Sunday 23:59 (UTC+8).
```suggestion
3. All matches will be held between Friday 18:00 and Sunday 23:59 (UTC+8).
```

2022-09-20 14:47 UTC, RushFTK reviewed
更新一些讨论结果

2022-09-20 14:47 UTC, RushFTK commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +1. Please send the host a **private message** and **fill [this form](https://wj.qq.com/s2/9902248/95cf/)** to register.
- all players must join QQ Group

2022-09-20 14:47 UTC, RushFTK commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +   - During phase 2 and 4, picks start in *decreasing* order, from the 16th to the 1st captain. -->
定板蛇形

2022-09-20 14:47 UTC, RushFTK commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +   - The room settings are `Game mode: "osu!mania"`, `Team mode: "Team Vs"` and `Score mode: "ScoreV2"`. The room name must follow the pattern of `GBC2 Spr: ({TeamRed}) vs ({TeamBlue})`.
```suggestion
   - The room settings are `Game mode: "osu!mania"`, `Team mode: "Team Vs"` and `Score mode: "ScoreV2"`. The room name must follow the pattern of `GBC2 Aut: ({TeamRed}) vs ({TeamBlue})`.
```

2022-09-20 14:47 UTC, RushFTK commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +   - Mappools #1 & #2: 13 beatmaps
```suggestion
   - Mappools #1 & #2: 15 beatmaps
```

2022-09-20 14:47 UTC, RushFTK commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +   - mappool #3: 15 beatmaps.
```suggestion
   - mappool #3: 17 beatmaps.
```

2022-09-20 14:47 UTC, RushFTK commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +4. The mappool will be played in the order listed above.
SV1, RC1, RC2, RC3, LN1, LN2, HB1, HB2

2022-09-21 02:20 UTC, RushFTK reviewed
Add some changes from last review.

2022-09-21 02:20 UTC, RushFTK commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +| Qualifier showcase | 2022-10-07 (20:00 UTC+8) |
```suggestion
| Qualifier showcase | 2022-10-08 (20:00 UTC+8) |
```

2022-09-21 02:20 UTC, RushFTK commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +| Mappool selector | *TBA* |
```suggestion
| Mappool selector | ::{ flag=CN }:: [\[GB\]yobrevelc](https://osu.ppy.sh/users/14128407), ::{ flag=CN }:: [Hylotl](https://osu.ppy.sh/users/18270260), ::{ flag=CN }:: [\[GB\]Luoxuan0327](https://osu.ppy.sh/users/8586018), ::{ flag=CN }:: [\[GB\]Mafufu](https://osu.ppy.sh/users/10884561), ::{ flag=CN }:: [\[GB\]Sanae](https://osu.ppy.sh/users/11238501), ::{ flag=CN }:: [Yueast 2018](https://osu.ppy.sh/users/13953619) |
```

2022-09-21 02:20 UTC, RushFTK commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +6. Host have rights to request VOD at any point.
```suggestion
```

2022-09-21 02:20 UTC, RushFTK commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +8. Referee **nolonger** have right to temporary modify rules on matches they responsible for.
```suggestion
```

2022-09-21 02:20 UTC, RushFTK commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +5. If no referee is available at match time, the match will be postponed.
```suggestion
```

2022-09-21 02:20 UTC, RushFTK commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +   - Semifinals and Finals use mappool #3.
```suggestion
   - Quarterfinals, Semifinals and Finals use separate mappool (#3 ,#4 ,#5 ).
```

2022-09-21 02:20 UTC, RushFTK commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +3. The maps for each round will be announced by the mappool selectors on the Sunday before the actual matches take place.
```suggestion
3. The maps for each round will be announced by the mappool selectors on the official stream, on the Sunday before the actual matches take place.
```

2022-09-21 02:20 UTC, RushFTK commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +4. Match scheduling will be handled by the host.
```suggestion
4. The match schedules for each round will be announced by the host on this page, as well as the information sheet, on the Sunday before the matches take place.
```

2022-09-21 02:20 UTC, RushFTK commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +    - The minimum amount of required players is defined as the amount of players needed to play a beatmap.
```suggestion
    - The minimum amount of required players is the amount of players needed to play a beatmap without any vacant spots in the lobby (i.e. 3 participants must be present for the match to begin).
```

2022-09-21 02:20 UTC, RushFTK commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +1. Please send the host a **private message** and **fill [this form](https://wj.qq.com/s2/9902248/95cf/)** to register.
```suggestion
1. Please send the host a **private message** and **fill [this form](https://wj.qq.com/s2/9902248/95cf/)** to register. 
   - Player **must** join [this QQ group](https://jq.qq.com/?_wv=1027&k=zqBeTqMW) after register.
```

2022-09-21 02:20 UTC, RushFTK commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +2. The Qualifier pool contains 8 maps, all of which will use [FreeMod](/wiki/Game_modifier#freemod) rules.
```suggestion
2. The Qualifier pool contains 8 maps, all of which will use [FreeMod](/wiki/Game_modifier#freemod) rules, organised as such:
   - Rice: 3 beatmaps
   - LN 2 beatmaps
   - Hybrid: 2 beatmaps
   - SV: 1 beatmap
```

2022-09-21 02:20 UTC, RushFTK commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +4. The mappool will be played in the order listed above.
```suggestion
4. The mappool will be played in the following order: SV1, RC1, RC2, RC3, LN1, LN2, HB1, HB2. Players may not ask to play the pool in any other order.
   - Player may skip playing any beatmap on their second run.
```

2022-09-21 02:20 UTC, RushFTK commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +   - Player also have rights to forfeit second runs.
```suggestion
```

2022-09-21 02:22 UTC, RushFTK commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +4. During the picking phase, picks start in *increasing* order, from the 1st to the 16th captain. The picks repeat four times, such that every captain gets to choose 4 players.
```suggestion
4. During the picking phase, the pick order consists of 2 phases that repeat twice, such that every captains gets to choose 4 players.
   - During phase 1 and 3, picks start in *increasing* order, from the 1st to the 16th captain.
   - During phase 2 and 4, picks start in *decreasing* order, from the 16th to the 1st captain.
```

2022-09-21 02:25 UTC, merged